# ============================================
# UnifiedHealth Platform - Trivy Secret Detection
# Configuration for detecting hardcoded secrets
# ============================================

# Enable secret scanning
enable-builtin-rules: true

# Custom secret detection rules
rules:
  # AWS Credentials
  - id: aws-access-key
    category: AWS
    title: AWS Access Key
    severity: CRITICAL
    regex: '(?i)(aws_access_key_id|aws_secret_access_key)\s*=\s*["\']?[A-Z0-9]{20}["\']?'
    keywords:
      - aws_access_key
      - aws_secret_access_key

  - id: aws-secret-key
    category: AWS
    title: AWS Secret Key
    severity: CRITICAL
    regex: 'AKIA[0-9A-Z]{16}'
    keywords:
      - AKIA

  # Azure Credentials
  - id: azure-client-secret
    category: Azure
    title: Azure Client Secret
    severity: CRITICAL
    regex: '(?i)(azure_client_secret|AZURE_CLIENT_SECRET)\s*=\s*["\']?[A-Za-z0-9~._-]{34,}["\']?'
    keywords:
      - azure_client_secret
      - AZURE_CLIENT_SECRET

  # Database Credentials
  - id: database-connection-string
    category: Database
    title: Database Connection String
    severity: CRITICAL
    regex: '(?i)(mongodb|mysql|postgres|postgresql)://[^:]+:[^@]+@'
    keywords:
      - mongodb://
      - mysql://
      - postgres://
      - postgresql://

  - id: database-password
    category: Database
    title: Database Password
    severity: HIGH
    regex: '(?i)(db_password|database_password|DB_PASS)\s*=\s*["\']?[A-Za-z0-9!@#$%^&*]{8,}["\']?'
    keywords:
      - db_password
      - database_password
      - DB_PASS

  # API Keys
  - id: generic-api-key
    category: API
    title: Generic API Key
    severity: HIGH
    regex: '(?i)(api[_-]?key|apikey|api[_-]?secret)\s*[=:]\s*["\']?[A-Za-z0-9_\-]{20,}["\']?'
    keywords:
      - api_key
      - apikey
      - api_secret

  - id: stripe-key
    category: Payment
    title: Stripe API Key
    severity: CRITICAL
    regex: '(sk|pk)_(test|live)_[0-9a-zA-Z]{24,}'
    keywords:
      - sk_test
      - sk_live
      - pk_test
      - pk_live

  # JWT Secrets
  - id: jwt-secret
    category: Authentication
    title: JWT Secret
    severity: HIGH
    regex: '(?i)(jwt[_-]?secret|jwt[_-]?key)\s*=\s*["\']?[A-Za-z0-9_\-]{32,}["\']?'
    keywords:
      - jwt_secret
      - jwt_key
      - JWT_SECRET

  # Private Keys
  - id: private-key
    category: Cryptography
    title: Private Key
    severity: CRITICAL
    regex: '-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'
    keywords:
      - BEGIN PRIVATE KEY
      - BEGIN RSA PRIVATE KEY
      - BEGIN EC PRIVATE KEY

  # OAuth Secrets
  - id: oauth-client-secret
    category: OAuth
    title: OAuth Client Secret
    severity: HIGH
    regex: '(?i)(client[_-]?secret|oauth[_-]?secret)\s*=\s*["\']?[A-Za-z0-9_\-]{32,}["\']?'
    keywords:
      - client_secret
      - oauth_secret

  # Healthcare-Specific Secrets
  - id: hipaa-encryption-key
    category: Healthcare
    title: HIPAA Encryption Key
    severity: CRITICAL
    regex: '(?i)(hipaa[_-]?key|phi[_-]?encryption[_-]?key)\s*=\s*["\']?[A-Za-z0-9+/]{32,}["\']?'
    keywords:
      - hipaa_key
      - phi_encryption_key

  - id: fhir-api-key
    category: Healthcare
    title: FHIR API Key
    severity: HIGH
    regex: '(?i)(fhir[_-]?api[_-]?key|fhir[_-]?token)\s*=\s*["\']?[A-Za-z0-9_\-]{20,}["\']?'
    keywords:
      - fhir_api_key
      - fhir_token

  # Session Secrets
  - id: session-secret
    category: Session
    title: Session Secret
    severity: HIGH
    regex: '(?i)(session[_-]?secret|cookie[_-]?secret)\s*=\s*["\']?[A-Za-z0-9_\-]{32,}["\']?'
    keywords:
      - session_secret
      - cookie_secret

  # Generic Passwords
  - id: generic-password
    category: Password
    title: Generic Password
    severity: MEDIUM
    regex: '(?i)(password|passwd|pwd)\s*[=:]\s*["\'](?!.*\$\{)[A-Za-z0-9!@#$%^&*]{8,}["\']'
    keywords:
      - password
      - passwd
      - pwd

  # Email Service Keys
  - id: sendgrid-api-key
    category: Email
    title: SendGrid API Key
    severity: HIGH
    regex: 'SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}'
    keywords:
      - SG.

  # Cloud Storage Keys
  - id: s3-bucket-key
    category: Storage
    title: S3 Bucket Access Key
    severity: HIGH
    regex: '(?i)(s3[_-]?bucket|s3[_-]?key)\s*=\s*["\']?[A-Za-z0-9_\-/]{20,}["\']?'
    keywords:
      - s3_bucket
      - s3_key

# Allowlist patterns (paths to exclude from secret scanning)
allowlist:
  paths:
    - .git/
    - node_modules/
    - vendor/
    - "*.test.ts"
    - "*.test.tsx"
    - "*.spec.ts"
    - "*.spec.tsx"
    - __tests__/
    - __mocks__/
    - "*.md"
    - .env.example
    - .env.*.example
    - docs/

  # Allowlist specific patterns (false positives)
  patterns:
    - 'example'
    - 'sample'
    - 'test'
    - 'demo'
    - 'placeholder'
    - 'your-'
    - 'your_'
    - 'xxx'
    - 'yyy'
    - 'zzz'
    - '<your-'
    - '${.*}'
    - '\$\{.*\}'

# Global allow/deny rules
global:
  # Exclude test/example files
  exclude-patterns:
    - '\.example$'
    - '\.sample$'
    - '\.template$'
    - '-example\.'
    - '-sample\.'
    - '-template\.'

  # Minimum entropy threshold (0.0 to 8.0)
  # Higher values = fewer false positives but might miss some secrets
  entropy-threshold: 4.5

  # Minimum secret length
  min-length: 12

# Notification settings
notifications:
  # Webhook URL for secret detection alerts (optional)
  # webhook-url: https://your-webhook-url.com

  # Email notifications (optional)
  # email: security@unifiedhealth.com

  # Slack notifications (optional)
  # slack-webhook: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
