/**
 * Production Sign-Off Report Generator
 * Generates formatted sign-off documentation
 */

import { VerificationReport } from './types';
import * as fs from 'fs';
import * as path from 'path';

export function generateSignOffReport(report: VerificationReport): string {
  const lines: string[] = [];

  lines.push('# PRODUCTION SIGN-OFF REPORT');
  lines.push('');
  lines.push(`**Platform:** ${report.platform}`);
  lines.push(`**Version:** ${report.version}`);
  lines.push(`**Environment:** ${report.environment}`);
  lines.push(`**Generated:** ${report.timestamp.toISOString()}`);
  lines.push(`**Generated By:** ${report.generatedBy}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Overall Status
  lines.push('## Overall Status');
  lines.push('');
  const statusEmoji = report.overallStatus === 'PASSED' ? '✅' :
                      report.overallStatus === 'FAILED' ? '❌' :
                      report.overallStatus === 'WARNING' ? '⚠️' : '⏭️';
  lines.push(`**Status:** ${statusEmoji} ${report.overallStatus}`);
  lines.push(`**Production Ready:** ${report.productionReady ? '✅ YES' : '❌ NO'}`);
  lines.push('');

  // Summary Table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Total Agents | ${report.summary.totalAgents} |`);
  lines.push(`| Passed Agents | ${report.summary.passedAgents} |`);
  lines.push(`| Failed Agents | ${report.summary.failedAgents} |`);
  lines.push(`| Total Checks | ${report.summary.totalChecks} |`);
  lines.push(`| Passed Checks | ${report.summary.passedChecks} |`);
  lines.push(`| Failed Checks | ${report.summary.failedChecks} |`);
  lines.push('');

  // Agent Sign-Off Section
  lines.push('## Agent Sign-Off');
  lines.push('');
  lines.push('| Agent | Status | Checks Passed |');
  lines.push('|-------|--------|---------------|');

  for (const agent of report.agents) {
    const agentStatus = agent.status === 'PASSED' ? '✅ APPROVED' :
                        agent.status === 'FAILED' ? '❌ BLOCKED' :
                        agent.status === 'WARNING' ? '⚠️ WARNING' : '⏭️ SKIPPED';
    lines.push(`| ${agent.agentName} | ${agentStatus} | ${agent.summary.passed}/${agent.summary.total} |`);
  }
  lines.push('');

  // Detailed Results
  lines.push('## Detailed Results');
  lines.push('');

  for (const agent of report.agents) {
    lines.push(`### ${agent.agentName}`);
    lines.push('');
    lines.push(`**Type:** ${agent.agentType}`);
    lines.push(`**Status:** ${agent.status}`);
    lines.push(`**Execution Time:** ${agent.executionTime}ms`);
    lines.push('');

    if (agent.checks.length > 0) {
      lines.push('| Check | Status | Details |');
      lines.push('|-------|--------|---------|');

      for (const check of agent.checks) {
        const checkStatus = check.status === 'PASSED' ? '✅' :
                           check.status === 'FAILED' ? '❌' :
                           check.status === 'WARNING' ? '⚠️' : '⏭️';
        const details = check.details ? check.details.substring(0, 50) : '-';
        lines.push(`| ${check.name} | ${checkStatus} ${check.status} | ${details} |`);
      }
    }
    lines.push('');
  }

  // Final Sign-Off
  lines.push('---');
  lines.push('');
  lines.push('## Final Sign-Off');
  lines.push('');
  lines.push('```');
  lines.push('PRODUCTION SIGN-OFF:');

  for (const agent of report.agents) {
    const status = agent.status === 'PASSED' ? 'APPROVED' :
                   agent.status === 'FAILED' ? 'BLOCKED' : agent.status;
    lines.push(`□ ${agent.agentName}: ${status}`);
  }

  lines.push('');
  lines.push(`FINAL STATUS: [${report.overallStatus}]`);
  lines.push(`DEPLOYMENT DATE: [${new Date().toISOString().split('T')[0]}]`);
  lines.push(`LOCK STATUS: [${report.productionReady ? 'READY TO LOCK' : 'NOT READY'}]`);
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

// Run if executed directly
if (require.main === module) {
  const reportsDir = path.join(__dirname, '../reports');
  const files = fs.readdirSync(reportsDir).filter(f => f.endsWith('.json'));

  if (files.length === 0) {
    console.error('No verification reports found. Run verification first.');
    process.exit(1);
  }

  // Get latest report
  const latestFile = files.sort().pop()!;
  const reportPath = path.join(reportsDir, latestFile);
  const report: VerificationReport = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));

  const markdown = generateSignOffReport(report);
  const outputPath = path.join(reportsDir, `SIGN-OFF-${Date.now()}.md`);
  fs.writeFileSync(outputPath, markdown);

  console.log('Sign-off report generated:', outputPath);
  console.log('');
  console.log(markdown);
}
